# Environment Variables required to be set in circleci web config
#
# LOWER_AWS_KEY=
# LOWER_AWS_SECRET=
# UPPER_AWS_KEY=
# UPPER_AWS_SECRET=

version: 2.1

executors:
  node:
    docker:
    - image: cimg/node:12.13

commands:
  restore-npm-cache:
    steps:
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package-lock.json" }}
  save-npm-cache:
    steps:
      - save_cache:
          paths:
            - ./node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - cache-dependencies:
        filters:
          branches:
            only: 
            - /.*/
          tags:
            only: 
            - /.*/
    - npm-test:
        requires: [cache-dependencies]
        filters:
          branches:
            only: 
            - /.*/
          tags:
            only: 
            - /.*/
    - test-lint:
        requires: [cache-dependencies]
        filters:
          branches:
            only:
            - /.*/
          tags:
            only:
            - /.*/
    - build-package:
        requires: [npm-test, test-lint]
        filters:
          branches:
            only:
            - master
          tags:
            only:
            - production
            - staging
            - mint
            - demo
            - venus
    - deploy-package:
        requires: [build-package]
        filters:
          branches:
            only:
            - master
          tags:
            only:
            - demo
            - venus
            - mint
        context: sba-gov-lower
    - hold:
        type: approval
        requires: [build-package]
        filters:
          branches:
            ignore:
            - /.*/
          tags:
            only:
            - production
            - staging
        context: sba-gov-upper
    - deploy-package-serverless-with-approval:
        requires: [hold]
        filters:
          branches:
            ignore:
            - /.*/
          tags:
            only:
            - staging
            - production
        context: sba-gov-upper
jobs:
  cache-dependencies:
    executor: node
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: install dependencies
          command: |
            npm install --silent --no-save
      - save-npm-cache
  npm-test:
    executor: node
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: run mocha
          command: |
            npm test
  test-lint:
    executor: node
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: run lint
          command: |
            npm run lint-no-fix
  build-package:
    executor: node
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: create zip package
          command: |
            mkdir build
            mkdir workspace
            cp package.json build/
            cp -R src/* build/
            cd build
            find . -name '*.test.js' -delete
            find . -name '*.integration-test.js' -delete
            npm i --prod --silent
            rm package.json
            zip -r -q ../workspace/sba-gov-content-api.zip .
            cd ..
            rm -rf build
      - persist_to_workspace:
          root: workspace
          paths:
            - sba-gov-content-api.zip
  deploy-package:
    executor: node
    steps:
    - checkout
    - attach_workspace:
        at: workspace
    - run:
          name: deploy
          shell: /bin/bash -eo pipefail
          command: |
            if [ -z "${CIRCLE_BRANCH}" ]	       
              then	
                TARGET_ENVIRONMENT=${CIRCLE_TAG}	
              else	
                TARGET_ENVIRONMENT=${CIRCLE_BRANCH}	
              fi	

              case $TARGET_ENVIRONMENT in	
                master)	
                  export ENVIRONMENT=mint	
                  ;;
                *)	
                  export ENVIRONMENT=${CIRCLE_TAG}	
                  ;;	
              esac

              npm i -g serverless
              serverless deploy --stage ${ENVIRONMENT}

  deploy-package-serverless-with-approval:
    executor: node
    steps:
    - checkout
    - attach_workspace:
        at: workspace
    - run:
          name: deploy
          shell: /bin/bash -eo pipefail
          command: |

            npm i -g serverless
            serverless deploy --stage ${CIRCLE_TAG}

